# Generated by Django 3.2.6 on 2022-02-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessao', '0006_remove_sessao_qtd_assentos_livres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assento_vendido', models.IntegerField(verbose_name='Número da Sala')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('num_sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.sessao')),
            ],
            options={
                'verbose_name': 'Vendas',
                'ordering': ['criado_em'],
            },
        ),
    ]
