# Generated by Django 3.2.6 on 2022-06-08 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingresso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'ordering': ['criado_em'], 'verbose_name': 'Venda'},
        ),
        migrations.AddField(
            model_name='vendas',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendas',
            name='assento_vendido',
            field=models.IntegerField(verbose_name='Assento Vendido'),
        ),
    ]
