# Generated by Django 3.2.6 on 2022-01-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atalho', models.SlugField(unique=True, verbose_name='Atalho')),
                ('num_sala', models.IntegerField(verbose_name='Número da Sala')),
                ('horario', models.DateTimeField(verbose_name='Horário')),
                ('dt_sessao', models.DateField(verbose_name='Data do Sessao')),
                ('qtd_assentos_livres', models.IntegerField(verbose_name='Assentos Livres')),
                ('valor_ingresso', models.FloatField(verbose_name='Valor Ingresso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('id_filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filme.filme')),
            ],
            options={
                'verbose_name': 'Sessao',
                'ordering': ['criado_em'],
            },
        ),
    ]
