# Generated by Django 3.2.6 on 2022-01-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
    ]
