# Generated by Django 3.2.6 on 2022-02-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
        ('sessao', '0002_alter_sessao_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='num_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala.sala'),
        ),
    ]
