# Generated by Django 3.2.6 on 2022-02-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0003_alter_sessao_num_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='num_sala',
        ),
    ]
