# Generated by Django 3.2.6 on 2022-02-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
        ('sessao', '0004_remove_sessao_num_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='num_sala',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sala.sala'),
            preserve_default=False,
        ),
    ]
