# Generated by Django 3.2.6 on 2022-01-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='duracao',
            field=models.TimeField(verbose_name='Duração do Filme'),
        ),
    ]
